[package]
name = "algorithm"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "leetcode_121", "leetcode_122", "leetcode_169", "leetcode_189", "leetcode_26", "leetcode_27", "leetcode_27_lib", "leetcode_80",
    "leetcode_88", "leetcode_88_lib",
]

[dependencies]
